# .github/workflows/preview.yml
# This is a basic workflow takes care of building and deploying
# catalog when creating merge request

name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed # pr-preview-action will do cleanup here, but build steps can be skipped

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# do not allow running multiple of pipelines for this PR in parallel
concurrency: preview-${{ github.ref }}

env:
  # BASE_URL for MyST build
  BASE_URL: /pr-preview/pr-${{ github.event.number }}/examples

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - name: Setup Node
        if: github.event.action != 'closed'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm # or pnpm / yarn
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install MyST
        if: github.event.action != 'closed'
        run: npm install -g mystmd
      - name: Build MyST HTML Assets
        if: github.event.action != 'closed'
        run: myst build --html
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _build/html/
